// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XIB-Iky7Gus_HgHySQpAwo4axqkbXMU',
    appId: '1:457726596117:web:332dbd1b0801563553aa1c',
    messagingSenderId: '457726596117',
    projectId: 'noterplus-2ad9d',
    authDomain: 'noterplus-2ad9d.firebaseapp.com',
    storageBucket: 'noterplus-2ad9d.appspot.com',
    measurementId: 'G-5FCV616E2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26dDBagNoj_aA8JQ1-rPWemCbz12kZ6k',
    appId: '1:457726596117:android:8ab7610e554292b053aa1c',
    messagingSenderId: '457726596117',
    projectId: 'noterplus-2ad9d',
    storageBucket: 'noterplus-2ad9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbj1E4YorkOnekbKvu1mdCTDPkbexQOXE',
    appId: '1:457726596117:ios:1e53cc6f818ba26c53aa1c',
    messagingSenderId: '457726596117',
    projectId: 'noterplus-2ad9d',
    storageBucket: 'noterplus-2ad9d.appspot.com',
    iosClientId:
        '457726596117-kjk88avv5vd23qaqvupifrj5u7d7pja3.apps.googleusercontent.com',
    iosBundleId: 'com.example.noterPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbj1E4YorkOnekbKvu1mdCTDPkbexQOXE',
    appId: '1:457726596117:ios:657850b3d1a6556653aa1c',
    messagingSenderId: '457726596117',
    projectId: 'noterplus-2ad9d',
    storageBucket: 'noterplus-2ad9d.appspot.com',
    iosClientId:
        '457726596117-2qhomjmh8k7cln2hvujosihh55j3ouru.apps.googleusercontent.com',
    iosBundleId: 'com.example.noterPlus.RunnerTests',
  );
}
